# Covid-19 Indonesia

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
df = pd.read_csv('covid_19_indonesia.csv')

In [3]:
df

Date Location ISO Code          Location  New Cases  New Deaths  \
0       3/1/2020             ID-JK       DKI Jakarta          2           0   
1       3/2/2020             ID-JK       DKI Jakarta          2           0   
2       3/2/2020               IDN         Indonesia          2           0   
3       3/2/2020             ID-RI              Riau          1           0   
4       3/3/2020             ID-JK       DKI Jakarta          2           0   
...          ...               ...               ...        ...         ...   
31817  9/15/2022             ID-SA    Sulawesi Utara         37           0   
31818  9/15/2022             ID-SB    Sumatera Barat         13           0   
31819  9/15/2022             ID-SS  Sumatera Selatan         16           0   
31820  9/15/2022             ID-SU    Sumatera Utara         50           0   
31821  9/16/2022               IDN         Indonesia       2358          27   

       New Recovered  New Active Cases  Total Cases  Total Deaths  \
0                  0                 2           39            20   
1                  0                 2           41            20   
2                  0                 2            2             0   
3                  0                 1            1             0   
4                  0                 2           43            20   
...              ...               ...          ...           ...   
31817              0                37        52770          1213   
31818              3                10       104640          2371   
31819              1                15        82198          3376   
31820              5                45       158866          3288   
31821           2997              -666      6405044        157876   

       Total Recovered  ...  Latitude New Cases per Million  \
0                   75  ... -6.204699                  0.18   
1                   75  ... -6.204699                  0.18   
2                    0  ... -0.789275                  0.01   
3                    1  ...  0.511648                  0.16   
4                   75  ... -6.204699                  0.18   
...                ...  ...       ...                   ...   
31817            50997  ...  1.259638                 14.01   
31818           102066  ... -0.850253                  2.36   
31819            78510  ... -3.216212                  1.95   
31820           154924  ...  2.191894                  3.36   
31821          6218708  ... -0.789275                  8.89   

       Total Cases per Million New Deaths per Million  \
0                         3.60                    0.0   
1                         3.78                    0.0   
2                         0.01                    0.0   
3                         0.16                    0.0   
4                         3.96                    0.0   
...                        ...                    ...   
31817                 19974.38                    0.0   
31818                 18959.11                    0.0   
31819                 10002.74                    0.0   
31820                 10680.15                    0.0   
31821                 24153.07                    0.1   

      Total Deaths per Million Total Deaths per 100rb Case Fatality Rate  \
0                         1.84                   0.18             51.28%   
1                         1.84                   0.18             48.78%   
2                         0.00                   0.00              0.00%   
3                         0.00                   0.00              0.00%   
4                         1.84                   0.18             46.51%   
...                        ...                    ...                ...   
31817                   459.14                  45.91              2.30%   
31818                   429.59                  42.96              2.27%   
31819                   410.83                  41.08              4.11%   
31820                   221.04  

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Date                         31822 non-null  object 
 1   Location ISO Code            31822 non-null  object 
 2   Location                     31822 non-null  object 
 3   New Cases                    31822 non-null  int64  
 4   New Deaths                   31822 non-null  int64  
 5   New Recovered                31822 non-null  int64  
 6   New Active Cases             31822 non-null  int64  
 7   Total Cases                  31822 non-null  int64  
 8   Total Deaths                 31822 non-null  int64  
 9   Total Recovered              31822 non-null  int64  
 10  Total Active Cases           31822 non-null  int64  
 11  Location Level               31822 non-null  object 
 12  City or Regency              0 non-null      float64
 13  Province        

In [5]:
# mastiin apakah ada NAN apa nggak

df.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
City or Regency                31822
Province                         929
Country                            0
Continent                          0
Island                           929
Time Zone                        929
Special Status                 27264
Total Regencies                    0
Total Cities                     901
Total Districts                    0
Total Urban Villages             904
Total Rural Villages             929
Area (km2)                         0
Population                         0
Population Density                 0
L

In [6]:
# to sum how many object types in the dataframe

isobject = df.dtypes == 'object'
isobject.sum()
# df.dtypes

12

In [7]:
df['Case Fatality Rate'].unique()

array(['51.28%', '48.78%', '0.00%', ..., '6.20%', '7.67%', '7.79%'],
      dtype=object)

In [8]:
import statistics

df['Total Cities'] = statistics.mode(df['Total Cities'])
df['Total Rural Villages'] = statistics.mode(df['Total Rural Villages'])
df['Total Urban Villages'] = statistics.mode(df['Total Urban Villages'])


In [9]:
df['Growth Factor of New Cases'] = df['Growth Factor of New Cases'].fillna(df['Growth Factor of New Cases'].mean())
df['Growth Factor of New Deaths'] = df['Growth Factor of New Deaths'].fillna(df['Growth Factor of New Deaths'].mean()) 


In [10]:
df = df.drop(['City or Regency', 'Special Status','Province', 'Island', 'Time Zone'], axis=1)

In [11]:
# df2 = df.drop([])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Date                         31822 non-null  object 
 1   Location ISO Code            31822 non-null  object 
 2   Location                     31822 non-null  object 
 3   New Cases                    31822 non-null  int64  
 4   New Deaths                   31822 non-null  int64  
 5   New Recovered                31822 non-null  int64  
 6   New Active Cases             31822 non-null  int64  
 7   Total Cases                  31822 non-null  int64  
 8   Total Deaths                 31822 non-null  int64  
 9   Total Recovered              31822 non-null  int64  
 10  Total Active Cases           31822 non-null  int64  
 11  Location Level               31822 non-null  object 
 12  Country                      31822 non-null  object 
 13  Continent       

In [12]:
# sn.heatmap(df.corr(), annot=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Date                         31822 non-null  object 
 1   Location ISO Code            31822 non-null  object 
 2   Location                     31822 non-null  object 
 3   New Cases                    31822 non-null  int64  
 4   New Deaths                   31822 non-null  int64  
 5   New Recovered                31822 non-null  int64  
 6   New Active Cases             31822 non-null  int64  
 7   Total Cases                  31822 non-null  int64  
 8   Total Deaths                 31822 non-null  int64  
 9   Total Recovered              31822 non-null  int64  
 10  Total Active Cases           31822 non-null  int64  
 11  Location Level               31822 non-null  object 
 12  Country                      31822 non-null  object 
 13  Continent       

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

In [15]:
df['Case Fatality Rate'] = df['Case Fatality Rate'].apply(lambda x : x.replace('%', ''))
df['Case Fatality Rate'] = df['Case Fatality Rate'].apply(lambda x: float(x))

df['Case Fatality Rate']

0        51.28
1        48.78
2         0.00
3         0.00
4        46.51
         ...  
31817     2.30
31818     2.27
31819     4.11
31820     2.07
31821     2.46
Name: Case Fatality Rate, Length: 31822, dtype: float64

In [16]:
df['Case Recovered Rate'] = df['Case Recovered Rate'].apply(lambda x : x.replace('%', ''))
df['Case Recovered Rate'] = df['Case Recovered Rate'].apply(lambda x: float(x))

df['Case Recovered Rate']

0        192.31
1        182.93
2          0.00
3        100.00
4        174.42
          ...  
31817     96.64
31818     97.54
31819     95.51
31820     97.52
31821     97.09
Name: Case Recovered Rate, Length: 31822, dtype: float64

In [17]:
# ob = df.dtypes == 'object'
# ob.sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Date                         31822 non-null  datetime64[ns]
 1   Location ISO Code            31822 non-null  object        
 2   Location                     31822 non-null  object        
 3   New Cases                    31822 non-null  int64         
 4   New Deaths                   31822 non-null  int64         
 5   New Recovered                31822 non-null  int64         
 6   New Active Cases             31822 non-null  int64         
 7   Total Cases                  31822 non-null  int64         
 8   Total Deaths                 31822 non-null  int64         
 9   Total Recovered              31822 non-null  int64         
 10  Total Active Cases           31822 non-null  int64         
 11  Location Level               31822 non-nu

In [18]:
# obj = ['Location ISO Code', 'Location','Location Level', 'Country', 'Continent']

# for i in obj:
#     df[i] = df[i].astype('category')
    
# df.info()

In [19]:
obj = ['Location ISO Code', 'Location','Location Level', 'Country', 'Continent']
df = df.drop(obj, axis=1)

In [20]:
col = df.columns
# col = col.drop('Growth Factor of New Cases')
col = col.drop('Date')

In [21]:
X = df[col]
y = df['Growth Factor of New Cases']

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.3, random_state=101)

In [36]:
from sklearn.metrics import mean_squared_error, r2_score

### KNNEIGHBORS

In [45]:
# KNWIGHBORS 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline

knn = KNeighborsRegressor(n_neighbors=2)
knn = knn.fit(X_train, y_train)

In [46]:
knn.score(X_train, y_train)

0.591337752636208

In [47]:
knn.score(X_test, y_test)

-0.248438121543608

In [48]:
y_predknn = knn.predict(X_test)
y_predknn

array([1.16339758, 0.95      , 0.735     , ..., 1.415     , 1.015     ,
       0.295     ])

In [49]:
mse_knn = mean_squared_error(y_test, y_predknn)
mse_knn

10.897998884772685

In [50]:
rmse_knn = np.sqrt(mse_knn)
rmse_knn

3.30121172977025

In [51]:
r2_knn = r2_score(y_test, y_predknn)
r2_knn

-0.248438121543608

### DECISION TREE

In [26]:
from sklearn import tree

dct = tree.DecisionTreeRegressor(max_depth=3, criterion='squared_error')
dct = dct.fit(X_train, y_train)

In [27]:
dct.score(X_train, y_train)

0.9427804586989523

In [28]:
dct.score(X_test, y_test)

0.8812710090312638

In [35]:
pred_dct = dct.predict(X_test)
pred_dct

array([0.71586124, 0.71586124, 0.71586124, ..., 0.71586124, 1.69934861,
       1.69934861])

In [37]:
mse = mean_squared_error(y_test, pred_dct)
mse

1.0364217407648884

In [38]:
rmse = np.sqrt(mse)
rmse

1.0180480051377185

In [39]:
r2 = r2_score(y_test, pred_dct)
r2

0.8812710090312638

### GRADIENT BOOSTING 

In [52]:
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
# from sklearn.model_selection import 

reg = GradientBoostingRegressor(random_state=7, learning_rate=0.01)
reg = reg.fit(X_train, y_train)

In [53]:
reg.score(X_train, y_train)

0.8465557815289917

In [54]:
reg.score(X_train, y_train)

0.8465557815289917

In [55]:
y_predreg = reg.predict(X_test)
y_predreg

array([0.82681423, 1.00761479, 1.10915158, ..., 1.11439816, 1.28262886,
       1.461094  ])

In [56]:
mse = mean_squared_error(y_test, y_predreg)
mse

2.303123310547004

In [58]:
rmse = np.sqrt(mse)
rmse

1.5176044644593676

In [59]:
r2reg = r2_score(y_test, y_predreg)
r2reg

0.736161934874104

In [32]:
y

0        1.326795
1        1.000000
2        1.326795
3        1.326795
4        1.000000
           ...   
31817    2.850000
31818    6.500000
31819    3.200000
31820    1.920000
31821    0.890000
Name: Growth Factor of New Cases, Length: 31822, dtype: float64

In [33]:
reg.predict(X_train[0:5])

array([1.27698952, 1.13767645, 0.93172208, 1.05713002, 0.78708323])

In [34]:
df

Date  New Cases  New Deaths  New Recovered  New Active Cases  \
0     2020-03-01          2           0              0                 2   
1     2020-03-02          2           0              0                 2   
2     2020-03-02          2           0              0                 2   
3     2020-03-02          1           0              0                 1   
4     2020-03-03          2           0              0                 2   
...          ...        ...         ...            ...               ...   
31817 2022-09-15         37           0              0                37   
31818 2022-09-15         13           0              3                10   
31819 2022-09-15         16           0              1                15   
31820 2022-09-15         50           0              5                45   
31821 2022-09-16       2358          27           2997              -666   

       Total Cases  Total Deaths  Total Recovered  Total Active Cases  \
0               39            20               75                 -56   
1               41            20               75                 -54   
2                2             0                0                   2   
3                1             0                1                   0   
4               43            20               75                 -52   
...            ...           ...              ...                 ...   
31817        52770          1213            50997                 560   
31818       104640          2371           102066                 203   
31819        82198          3376            78510                 312   
31820       158866          3288           154924                 654   
31821      6405044        157876          6218708               28460   

       Total Regencies  ...  Latitude  New Cases per Million  \
0                    1  ... -6.204699                   0.18   
1                    1  ... -6.204699                   0.18   
2                  416  ... -0.789275                   0.01   
3                   10  ...  0.511648                   0.16   
4                    1  ... -6.204699                   0.18   
...                ...  ...       ...                    ...   
31817               11  ...  1.259638                  14.01   
31818               12  ... -0.850253                   2.36   
31819               13  ... -3.216212                   1.95   
31820               25  ...  2.191894                   3.36   
31821              416  ... -0.789275                   8.89   

       Total Cases per Million  New Deaths per Million  \
0                         3.60                     0.0   
1                         3.78                     0.0   
2                         0.01                     0.0   
3                         0.16                     0.0   
4                         3.96                     0.0   
...                        ...                     ...   
31817                 19974.38                     0.0   
31818                 18959.11                     0.0   
31819                 10002.74                     0.0   
31820                 10680.15                     0.0   
31821                 24153.07                     0.1   

       Total Deaths per Million  Total Deaths per 100rb  Case Fatality Rate  \
0                          1.84                    0.18               51.28   
1                          1.84                    0.18               48.78   
2                          0.00                    0.00                0.00   
3                          0.00                    0.00                0.00   
4                          1.84                    0.18               46.51   
...                         ...                     ...                 ...   
31817                    459.14                   45.91                2.30   
31818                    429.59                   42.96                2.27   
31819                    410.83              